Fixes 32 - Method getDateModified of RSS reader doesn't iterate over different formats
laminas/laminas-feed pull request #33
Opened 2020-12-20 18:05 UTC by froschdesign

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

2020-12-23 18:13 UTC, weierophinney requested changes
Changes look reasonable to me. Please check the Psalm output, though, as you'll either need to correct some new issues, or add to the baseline:

- https://travis-ci.com/github/laminas/laminas-feed/jobs/464005564#L793

2020-12-24 12:54 UTC, froschdesign commented
@weierophinney 
> Please check the Psalm output, though, as you'll either need to correct some new issues…

Yes, there are massive problems with many bugs. But these are _old_ problems and not related to this pull request. No new problems are introduced with this PR.

---

Pslam reports the following problem for example:

> RedundantCastGivenDocblockType - test/Reader/Entry/AtomStandaloneEntryTest.php:150:39
>
> Redundant cast to array given docblock-provided type (see https://psalm.dev/263)
> $this->assertEquals($authors, (array) $entry->getAuthors());

https://travis-ci.com/github/laminas/laminas-feed/jobs/464005564#L881-L882

But the problem is not the redundant cast, the problem is the related DocBlock:

https://github.com/laminas/laminas-feed/blob/db2d64788a25ab10b77c6301b42692b2953bcc3c/src/Reader/Feed/FeedInterface.php#L26-L31

It's not a array it's a collection or `null`:

https://github.com/laminas/laminas-feed/blob/db2d64788a25ab10b77c6301b42692b2953bcc3c/src/Reader/Collection/Author.php#L11-L27

https://github.com/laminas/laminas-feed/blob/db2d64788a25ab10b77c6301b42692b2953bcc3c/src/Reader/Feed/Rss.php#L124-L126

2020-12-24 12:55 UTC, froschdesign commented
There is a separate issue report for the wrong DocBlocks: #30

2021-01-04 19:12 UTC, weierophinney approved these changes

2021-01-04 19:14 UTC, merged